---
# Setup
random-seed: 42
num-runs: 1
epochs: 8
no-cuda: False

# Logging parameters
log-params:
  log-interval: 1
  logdir: 'demolog'
  metrics:
    weights: True
    loss: True
    accuracy: True
    test-accuracy: True
    cosine-dists:
      flag: True
      population-size: 10
    gradient-projections: False

# Training hyperparameters
hyperparams:
  batch-size: 256
  learning-rate: 0.01
  momentum: 0.9
  test-batch-size: 1000

# Network config
# Note: first hidden layer fixed at size 20 in case 2 hidden layers are used
network-config:
  two-hidden-layers: False
  num-hidden-neurons: 40

# Experimental settings
experiment-params:
  regularizer:
    ortho-reg: False
    dropout: False
  network-growth:
    flag: False
    at-start-flag: False
    epochs-before-growth: 40
    method: 'rotation_noise'
    noise-var: 0.64
    weight-norm: False